"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var react_1 = __importDefault(require("react"));
var Layout_1 = __importDefault(require("@theme/Layout"));
var Link_1 = __importDefault(require("@docusaurus/Link"));
var Section = function (_a) {
    var title = _a.title, children = _a.children;
    return ((0, jsx_runtime_1.jsxs)("section", { className: "mb-6", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-semibold mb-4", children: title }), children] }));
};
var ListItem = function (_a) {
    var title = _a.title, description = _a.description;
    return ((0, jsx_runtime_1.jsxs)("li", { className: "mb-4", children: [(0, jsx_runtime_1.jsx)("strong", { className: "font-medium", children: title }), (0, jsx_runtime_1.jsx)("p", { children: description })] }));
};
var LastUpdated = function () { return ((0, jsx_runtime_1.jsxs)("p", { className: "text-sm text-gray-600 dark:text-gray-500 mb-4", children: [(0, jsx_runtime_1.jsx)("strong", { children: "Last Updated:" }), " 25th May 2025"] })); };
var OurPledge = function () { return ((0, jsx_runtime_1.jsxs)(Section, { title: "Our Pledge", children: [(0, jsx_runtime_1.jsx)("p", { className: "mb-4", children: "We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation." }), (0, jsx_runtime_1.jsx)("p", { children: "We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community." })] })); };
var OurStandards = function () { return ((0, jsx_runtime_1.jsxs)(Section, { title: "Our Standards", children: [(0, jsx_runtime_1.jsx)("p", { className: "mb-4", children: "Examples of behavior that contributes to a positive environment for our community include:" }), (0, jsx_runtime_1.jsxs)("ul", { className: "list-disc list-inside mb-4", children: [(0, jsx_runtime_1.jsx)("li", { children: "Demonstrating empathy and kindness toward other people" }), (0, jsx_runtime_1.jsx)("li", { children: "Being respectful of differing opinions, viewpoints, and experiences" }), (0, jsx_runtime_1.jsx)("li", { children: "Giving and gracefully accepting constructive feedback" }), (0, jsx_runtime_1.jsx)("li", { children: "Accepting responsibility and apologizing to those affected by our mistakes, and learning from the experience" }), (0, jsx_runtime_1.jsx)("li", { children: "Focusing on what is best not just for us as individuals, but for the overall community" })] }), (0, jsx_runtime_1.jsx)("p", { className: "mb-4", children: "Examples of unacceptable behavior include:" }), (0, jsx_runtime_1.jsxs)("ul", { className: "list-disc list-inside mb-4", children: [(0, jsx_runtime_1.jsx)("li", { children: "The use of sexualized language or imagery, and sexual attention or advances of any kind" }), (0, jsx_runtime_1.jsx)("li", { children: "Trolling, insulting or derogatory comments, and personal or political attacks" }), (0, jsx_runtime_1.jsx)("li", { children: "Public or private harassment" }), (0, jsx_runtime_1.jsx)("li", { children: "Publishing others' private information, such as a physical or email address, without their explicit permission" }), (0, jsx_runtime_1.jsx)("li", { children: "Other conduct which could reasonably be considered inappropriate in a professional setting" })] })] })); };
var EnforcementResponsibilities = function () { return ((0, jsx_runtime_1.jsxs)(Section, { title: "Enforcement Responsibilities", children: [(0, jsx_runtime_1.jsx)("p", { className: "mb-4", children: "Community leaders are responsible for clarifying and enforcing our standards of acceptable behavior and will take appropriate and fair corrective action in response to any behavior that they deem inappropriate, threatening, offensive, or harmful." }), (0, jsx_runtime_1.jsx)("p", { children: "Community leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate." })] })); };
var Scope = function () { return ((0, jsx_runtime_1.jsx)(Section, { title: "Scope", children: (0, jsx_runtime_1.jsx)("p", { children: "This Code of Conduct applies within all community spaces, and also applies when an individual is officially representing the community in public spaces. Examples of representing our community include using an official e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event." }) })); };
var Enforcement = function () { return ((0, jsx_runtime_1.jsx)(Section, { title: "Enforcement", children: (0, jsx_runtime_1.jsx)("p", { children: "Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at Email. All complaints will be reviewed and investigated promptly and fairly. All community leaders are obligated to respect the privacy and security of the reporter of any incident." }) })); };
var EnforcementGuidelines = function () { return ((0, jsx_runtime_1.jsxs)(Section, { title: "Enforcement Guidelines", children: [(0, jsx_runtime_1.jsx)("p", { className: "mb-4", children: "Community leaders will follow these Community Impact Guidelines in determining the consequences for any action they deem in violation of this Code of Conduct:" }), (0, jsx_runtime_1.jsxs)("ol", { className: "list-decimal list-inside mb-4", children: [(0, jsx_runtime_1.jsx)(ListItem, { title: "Correction", description: (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Community Impact:" }), " Use of inappropriate language or other behavior deemed unprofessional or unwelcome in the community.", (0, jsx_runtime_1.jsx)("br", {}), (0, jsx_runtime_1.jsx)("strong", { children: "Consequence:" }), " A private, written warning from community leaders, providing clarity around the nature of the violation and an explanation of why the behavior was inappropriate. A public apology may be requested."] }) }), (0, jsx_runtime_1.jsx)(ListItem, { title: "Warning", description: (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Community Impact:" }), " A violation through a single incident or series of actions.", (0, jsx_runtime_1.jsx)("br", {}), (0, jsx_runtime_1.jsx)("strong", { children: "Consequence:" }), " A warning with consequences for continued behavior. No interaction with the people involved, including unsolicited interaction with those enforcing the Code of Conduct, for a specified period. Violating these terms may lead to a temporary or permanent ban."] }) }), (0, jsx_runtime_1.jsx)(ListItem, { title: "Temporary Ban", description: (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Community Impact:" }), " A serious violation of community standards, including sustained inappropriate behavior.", (0, jsx_runtime_1.jsx)("br", {}), (0, jsx_runtime_1.jsx)("strong", { children: "Consequence:" }), " A temporary ban from any interaction or public communication with the community for a specified period. Violating these terms may lead to a permanent ban."] }) }), (0, jsx_runtime_1.jsx)(ListItem, { title: "Permanent Ban", description: (0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [(0, jsx_runtime_1.jsx)("strong", { children: "Community Impact:" }), " Demonstrating a pattern of violation of community standards, including harassment of an individual, or disparagement of groups.", (0, jsx_runtime_1.jsx)("br", {}), (0, jsx_runtime_1.jsx)("strong", { children: "Consequence:" }), " A permanent ban from any sort of public interaction within the community."] }) })] })] })); };
var Attribution = function () { return ((0, jsx_runtime_1.jsxs)(Section, { title: "Attribution", children: [(0, jsx_runtime_1.jsxs)("p", { className: "mb-2", children: ["This Code of Conduct is adapted from the ", (0, jsx_runtime_1.jsx)(Link_1.default, { to: "https://www.contributor-covenant.org/", target: "_blank", rel: "noopener noreferrer", children: "Contributor Covenant" }), ", version 2.0."] }), (0, jsx_runtime_1.jsxs)("p", { children: ["For more details, visit ", (0, jsx_runtime_1.jsx)(Link_1.default, { to: "https://www.contributor-covenant.org/version/2/0/code_of_conduct/", target: "_blank", rel: "noopener noreferrer", children: "here" }), "."] })] })); };
var CodeOfConduct = function () { return ((0, jsx_runtime_1.jsx)(Layout_1.default, { children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-4xl mx-auto p-6 mt-5 mb-5 rounded-lg shadow-md", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-center text-2xl font-bold mb-5", children: "Code Of Conduct" }), (0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsx)(LastUpdated, {}), (0, jsx_runtime_1.jsx)(OurPledge, {}), (0, jsx_runtime_1.jsx)(OurStandards, {}), (0, jsx_runtime_1.jsx)(EnforcementResponsibilities, {}), (0, jsx_runtime_1.jsx)(Scope, {}), (0, jsx_runtime_1.jsx)(Enforcement, {}), (0, jsx_runtime_1.jsx)(EnforcementGuidelines, {}), (0, jsx_runtime_1.jsx)(Attribution, {})] })] }) })); };
exports.default = CodeOfConduct;
